:source-highlighter: pygments
:icons: font

= Chat application

== How to use

[source,shell]
----
git clone --branch dev --recursive git@github.com:polyglot-concurrency/erlang_chat_server.git chat_server
cd chat_server
rebar3 as prod release
_build/prod/rel/chat_server/bin/chat_server console
(chat_server@albert)1>
----


Fixture data added:

[source,shell]
----
> db:add_user("jhon", "aaaa"). <1>
ok
> db:add_user("ana", "bbbb").
ok
> db:add_user("mike", "cccc").
ok
> db:add_user("will", "dddd").
ok
> db:add_group("group2", "ana"). <2>
ok
> db:add_user_to_group("group2", "mike"). <3>
ok
> db:add_user_to_group("group2", "jhon").
ok
> db:add_user_to_group("group2", "will").
----

<1> Adding 3 users, the first parameter is the name, the secondone is the password.

<2> Creating a group, using the db interface (the recomended way is using the chat_client API). The user
creating the group is automatically added to it.

<3> Adding 3 others users to the group.

=== Login/logout client

[source,shell]
----
> chat_client:start(node()). <1>
> {_, Pmike} = chat_client:login("mike", "cccc").
{ok,<0.183.0>}
> chat_client:logout(Pmike).
ok
----

<1> chat_client is a process needed for interacting with the server, in order to start it you need to specify the name of the server node.

=== One to One chat

[source,shell]
----
> {_, Pana} = chat_client:login("ana", "bbbb").
{ok,<0.181.0>}
> {_, Pmike} = chat_client:login("mike", "cccc").
{ok,<0.183.0>}
> chat_client:send_msg(Pana, "mike", "hello mike").
ok
> {ok, Msgs} = chat_client:get_msgs(Pmike).
{ok,[{"ana","hello mike"}]}
----

=== Group chat

The following description is based on the test cases of the project.

[source,erlang]
----
    {_, Pana} = chat_client:login("ana", "bbbb"), <1>
    {_, Pmike} = chat_client:login("mike", "cccc"),
    {_, Pjhon} = chat_client:login("jhon", "aaaa"),

    chat_client:send_msg_to_group(Pana, "group2", "hello mike"), <2>
    chat_client:send_msg_to_group(Pana, "group2", "hello again"),
    chat_client:send_msg_to_group(Pjhon, "group2", "hello"),

    chat_client:send_msg(Pjhon, "will", "what's up?"), <3>

    {_, Pwill} = chat_client:login("will", "dddd"), <4>

    {ok, Msgs} = chat_client:get_msgs(Pmike), <5>
    {ok, MsgsPjhon} = chat_client:get_msgs(Pjhon),
    {ok, MsgsPana} = chat_client:get_msgs(Pana),
    {ok, MsgsPwill} = chat_client:get_msgs(Pwill),

    [
     ?_assertEqual([
                    {"group2:ana", "hello mike"}
                   , {"group2:ana", "hello again"}
                   , {"group2:jhon", "hello"}
                   ], Msgs) <6>
    ,?_assertEqual([
                    {"group2:ana", "hello mike"}
                   , {"group2:ana", "hello again"}
                   ], MsgsPjhon)
    ,?_assertEqual([
                    {"group2:jhon", "hello"}
                   ], MsgsPana)
    ,?_assertEqual([
                    {"group2:ana", "hello mike"}
                   , {"group2:ana", "hello again"}
                   , {"group2:jhon", "hello"}
                   , {"jhon", "what's up?"}
                   ], MsgsPwill)

    ].
----

<1> Login 3 users, the session is represented by
a Pid of an chat_user module process. The chat_user process is created in the node
where the login happend.

<2> Sending a group message to "group2" group. The sender is the first parameter,
and the lastone the message content.

<3> Sending a normal message to "will".

<4> Now is "will" loged in, the previos messages where stored,
and now are sended to this just created chat_user.

<5> Checking the messages of each user.

<6> "mike" messages, the format of the messages: the first component is
the sender name (when the messges came from a group chat it is included
its name too), the second is the text message .

=== Get list of users

[source,shell]
----
> chat_client:get_all_users_names().
["ana","jhon","mike"]
----

=== Cluster support

Lets use the client app:

[source,shell]
----
git clone --branch dev --recursive git@github.com:polyglot-concurrency/erlang_chat_client.git chat_client
cd chat_client
rebar3 as prod release
_build/prod/rel/chat_client/bin/chat_client console
(chat_client@albert)1> chat_client:start(chat_server@albert).
(chat_client@albert)2> {ok, Pana} = chat_client:login("ana", "bbbb").
{ok,<0.270.0>}
(chat_client@albert)3> chat_client:send_msg(Pana, "jhon", "hello").
ok
----

And lets go to turn on another node (a 3th one) with the client app.

[source,shell]
----
cp -R _build/prod ../client2
sed -i "s,chat_client,client2," ../client2/rel/chat_client/releases/0.1.0/vm.args
../client2/rel/chat_client/bin/chat_client console
(client2@albert)1> chat_client:start(chat_server@albert).
(client2@albert)2> {ok, Pjhon} = chat_client:login("jhon", "aaaa").
{ok,<0.271.0>}
(client2@albert)3> chat_client:get_msgs(Pjhon).
{ok,[{"ana","hello"}]}
----

== Apply dialyzer

    $ rebar3 dialyzer apps/chat_server/src/lib/chat_client.erl apps/chat_server/src/lib/db.erl apps/chat_server/src/lib/chat_user.erl apps/chat_server/src/lib/chat_server.erl
